import fs from 'fs';
import path from 'path';
import type { Exporter, ExportMeta } from './index';
import type { ProcessingResult } from '../agents/documentProcessor';
import { logger } from '../utils/logger';

const XML_DIR = path.resolve(process.env.XML_DIR ?? './output/xml');

function x(val: string | number | null | undefined): string {
  if (val === null || val === undefined) return '';
  return String(val)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function opt(xml: string, condition: unknown): string {
  return condition ? xml : '';
}

type InvoiceData = Extract<ProcessingResult & { success: true }, { documentType: 'invoice' }>['data'];
type StatementData = Extract<ProcessingResult & { success: true }, { documentType: 'bank_statement' }>['data'];

function buildInvoiceXml(inv: InvoiceData, meta: ExportMeta): string {
  const cur = x(inv.currency);
  const amt = (v: number | null | undefined) =>
    v != null ? `<cbc:Amount currencyID="${cur}">${x(v)}</cbc:Amount>` : '';

  const lineItems = inv.lineItems
    .map(
      (item, i) => `
    <cac:InvoiceLine>
      <cbc:ID>${i + 1}</cbc:ID>
      ${opt(`<cbc:InvoicedQuantity>${x(item.quantity)}</cbc:InvoicedQuantity>`, item.quantity != null)}
      ${amt(item.totalAmount).replace('<cbc:Amount', '<cbc:LineExtensionAmount').replace('</cbc:Amount>', '</cbc:LineExtensionAmount>')}
      ${opt(`<cac:TaxTotal><cbc:TaxAmount currencyID="${cur}">${x(item.taxAmount)}</cbc:TaxAmount></cac:TaxTotal>`, item.taxAmount != null)}
      <cac:Item><cbc:Description>${x(item.description)}</cbc:Description></cac:Item>
      ${opt(`<cac:Price><cbc:PriceAmount currencyID="${cur}">${x(item.unitPrice)}</cbc:PriceAmount></cac:Price>`, item.unitPrice != null)}
    </cac:InvoiceLine>`,
    )
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by accounting-agent on ${meta.processedAt} | source: ${x(meta.fileName)} -->
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2">
  <cbc:UBLVersionID>2.1</cbc:UBLVersionID>
  <cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID>
  ${opt(`<cbc:ID>${x(inv.invoiceNumber)}</cbc:ID>`, inv.invoiceNumber)}
  ${opt(`<cbc:IssueDate>${x(inv.issueDate)}</cbc:IssueDate>`, inv.issueDate)}
  ${opt(`<cbc:DueDate>${x(inv.dueDate)}</cbc:DueDate>`, inv.dueDate)}
  <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
  <cbc:DocumentCurrencyCode>${cur}</cbc:DocumentCurrencyCode>
  ${opt(`<cbc:Note>${x(inv.notes)}</cbc:Note>`, inv.notes)}

  <cac:AccountingSupplierParty>
    <cac:Party>
      <cac:PartyName><cbc:Name>${x(inv.issuer.name)}</cbc:Name></cac:PartyName>
      ${opt(`<cac:PartyTaxScheme>
        <cbc:CompanyID>${x(inv.issuer.taxId)}</cbc:CompanyID>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:PartyTaxScheme>`, inv.issuer.taxId)}
      ${opt(`<cac:Contact>
        <cbc:ElectronicMail>${x(inv.issuer.email)}</cbc:ElectronicMail>
      </cac:Contact>`, inv.issuer.email)}
    </cac:Party>
  </cac:AccountingSupplierParty>

  ${opt(`<cac:AccountingCustomerParty>
    <cac:Party>
      <cac:PartyName><cbc:Name>${x(inv.recipient?.name)}</cbc:Name></cac:PartyName>
      ${opt(`<cac:PartyTaxScheme>
        <cbc:CompanyID>${x(inv.recipient?.taxId)}</cbc:CompanyID>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:PartyTaxScheme>`, inv.recipient?.taxId)}
    </cac:Party>
  </cac:AccountingCustomerParty>`, inv.recipient)}

  ${opt(`<cac:PaymentMeans>
    <cbc:PaymentMeansCode>${x(inv.paymentMethod)}</cbc:PaymentMeansCode>
    ${opt(`<cbc:PaymentDueDate>${x(inv.dueDate)}</cbc:PaymentDueDate>`, inv.dueDate)}
  </cac:PaymentMeans>`, inv.paymentMethod)}

  ${opt(`<cac:TaxTotal>
    <cbc:TaxAmount currencyID="${cur}">${x(inv.totalTax)}</cbc:TaxAmount>
  </cac:TaxTotal>`, inv.totalTax != null)}

  <cac:LegalMonetaryTotal>
    ${opt(`<cbc:LineExtensionAmount currencyID="${cur}">${x(inv.subtotal)}</cbc:LineExtensionAmount>`, inv.subtotal != null)}
    ${opt(`<cbc:TaxExclusiveAmount currencyID="${cur}">${x(inv.subtotal)}</cbc:TaxExclusiveAmount>`, inv.subtotal != null)}
    ${opt(`<cbc:TaxInclusiveAmount currencyID="${cur}">${x(inv.totalAmount)}</cbc:TaxInclusiveAmount>`, inv.totalAmount != null)}
    ${opt(`<cbc:AllowanceTotalAmount currencyID="${cur}">${x(inv.discount)}</cbc:AllowanceTotalAmount>`, inv.discount != null)}
    ${opt(`<cbc:PayableAmount currencyID="${cur}">${x(inv.totalAmount)}</cbc:PayableAmount>`, inv.totalAmount != null)}
  </cac:LegalMonetaryTotal>
  ${lineItems}
</Invoice>`;
}

function buildStatementXml(bs: StatementData, meta: ExportMeta): string {
  const cur = x(bs.currency);

  const transactions = bs.transactions
    .map(
      (tx) => `
    <Transaction>
      ${opt(`<Date>${x(tx.date)}</Date>`, tx.date)}
      <Description>${x(tx.description)}</Description>
      ${opt(`<Reference>${x(tx.reference)}</Reference>`, tx.reference)}
      ${opt(`<Debit currencyID="${cur}">${x(tx.debit)}</Debit>`, tx.debit != null)}
      ${opt(`<Credit currencyID="${cur}">${x(tx.credit)}</Credit>`, tx.credit != null)}
      ${opt(`<Balance currencyID="${cur}">${x(tx.balance)}</Balance>`, tx.balance != null)}
      ${opt(`<Category>${x(tx.category)}</Category>`, tx.category)}
    </Transaction>`,
    )
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by accounting-agent on ${meta.processedAt} | source: ${x(meta.fileName)} -->
<BankStatement xmlns="urn:accounting-agent:bank-statement:1.0">
  ${opt(`<BankName>${x(bs.bankName)}</BankName>`, bs.bankName)}
  ${opt(`<AccountHolder>${x(bs.accountHolder)}</AccountHolder>`, bs.accountHolder)}
  ${opt(`<AccountNumber>${x(bs.accountNumber)}</AccountNumber>`, bs.accountNumber)}
  <Currency>${cur}</Currency>
  ${opt(`<PeriodStart>${x(bs.periodStart)}</PeriodStart>`, bs.periodStart)}
  ${opt(`<PeriodEnd>${x(bs.periodEnd)}</PeriodEnd>`, bs.periodEnd)}
  ${opt(`<OpeningBalance currencyID="${cur}">${x(bs.openingBalance)}</OpeningBalance>`, bs.openingBalance != null)}
  ${opt(`<ClosingBalance currencyID="${cur}">${x(bs.closingBalance)}</ClosingBalance>`, bs.closingBalance != null)}
  <Transactions>${transactions}
  </Transactions>
</BankStatement>`;
}

export class XmlExporter implements Exporter {
  readonly name = 'accounting-software-xml';

  async export(result: ProcessingResult & { success: true }, meta: ExportMeta): Promise<void> {
    fs.mkdirSync(XML_DIR, { recursive: true });

    const baseName = path.basename(meta.fileName, path.extname(meta.fileName));
    const timestamp = meta.processedAt.replace(/[:.]/g, '-').replace('T', '_').slice(0, 19);
    const outFile = path.join(XML_DIR, `${baseName}_${timestamp}.xml`);

    const xml =
      result.documentType === 'invoice'
        ? buildInvoiceXml(result.data, meta)
        : buildStatementXml(result.data, meta);

    fs.writeFileSync(outFile, xml, 'utf-8');
    logger.info(`XML: written`, { file: outFile });
  }
}
